---
- name: Install firmware
  pkgin:
    name:
      - intel-microcode-netbsd
      - iwn-firmware
    state: present

- name: Create symlink for intel microcode
  file:
    src: /usr/pkg/share/examples/rc.d/intel-microcode
    dest: /etc/rc.d/intel-microcode
    state: link

- name: Configure /etc/rc.conf for firmware
  lineinfile:
    path: /etc/rc.conf
    line: "{{ item.line }}"
  loop:
    - line: microcode=YES
