---
- name: Install go packages
  pkgin:
    name:
      - go120
      - go122
    state: present
  tags: ['pkg', 'golang']

- name: Create go symlink
  file:
    src: go122
    dest: /usr/pkg/bin/go
    state: link
  tags: ['golang']

- name: Create gofmt symlink
  file:
    src: gofmt122
    dest: /usr/pkg/bin/gofmt
    state: link
  tags: ['golang']
