---
- name: Install go packages
  pkgin:
    name:
      - go125
    state: present

- name: Create go symlink
  file:
    src: go125
    dest: /usr/pkg/bin/go
    state: link

- name: Create gofmt symlink
  file:
    src: gofmt125
    dest: /usr/pkg/bin/gofmt
    state: link
