---
- name: Install go packages
  pkgin:
    name:
      - go123
    state: present
  tags: ['pkg', 'golang']

- name: Create go symlink
  file:
    src: go123
    dest: /usr/pkg/bin/go
    state: link
  tags: ['golang']

- name: Create gofmt symlink
  file:
    src: gofmt123
    dest: /usr/pkg/bin/gofmt
    state: link
  tags: ['golang']
