---
- name: Ensure /etc/modules.conf exists
  shell: touch /etc/modules.conf
  args:
    creates: /etc/modules.conf

- name: Enable linux binary compatibility
  lineinfile:
    path: /etc/modules.conf
    line: "{{ item.line }}"
  loop:
    - line: mqueue
    - line: compat_linux

- name: Mount /emul/linux/proc
  mount:
    path: /emul/linux/proc
    src: procfs
    fstype: procfs
    state: mounted
    opts: ro

- name: Mount /emul/linux/dev/shm
  mount:
    path: /emul/linux/dev/shm
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: rw,-m1777

- name: Install required packages
  pkgin:
    name:
      - rpm2pkg
      - suse_base-15.5nb1
      - suse_binutils-15.5
    state: present
