---
- name: Ensure /etc/modules.conf exists
  shell: touch /etc/modules.conf
  args:
    creates: /etc/modules.conf
  tags: ['linux']

- name: Enable linux binary compatibility
  lineinfile:
    path: /etc/modules.conf
    line: compat_linux
  tags: ['linux']

- name: Mount /emul/linux/proc
  mount:
    path: /emul/linux/proc
    src: procfs
    fstype: procfs
    state: mounted
    opts: ro
  tags: ['linux', 'mount']

- name: Mount /emul/linux/dev/shm
  mount:
    path: /emul/linux/dev/shm
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: rw,-m1777
  tags: ['linux', 'mount']

- name: Install required packages
  pkgin:
    name:
      - rpm2pkg
      - suse_base-15.5nb1
      - suse_binutils-15.5
    state: present
  tags: ['pkg', 'linux']
