---
- name: Add user to needed groups
  user:
    name: "{{ target_user }}"
    groups: wheel,operator,wsrc
    append: yes
    shell: /usr/pkg/bin/bash
  tags: ['user']

- name: Fix HOME permissions
  file:
    path: "/home/{{ target_user }}"
    state: directory
    owner: "{{ target_user }}"
    group: users
    mode: '0750'
  tags: ['user']
